services:
  db:
    image: postgres
    healthcheck:
      test: pg_isready -U myuser -d client-api
      interval: 5s
      timeout: 3s
      retries: 3
    ports:
      - '5432'
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: client-api